### ISSUE TITLE
怎么解决certificate unknown

### ISSUE THREAD

**Issue by changzhn** [notedit/webcodecs-play#1]
Failed to establish a connection to quic-transport://localhost:4433/webcodecs: net::ERR_QUIC_PROTOCOL_ERROR.QUIC_TLS_CERTIFICATE_UNKNOWN (TLS handshake failure (ENCRYPTION_HANDSHAKE) 46: certificate unknown).

**Comment by hthetiot** [comment]
That most likely due the self signed certificate, it's not a bug, simply generate your own certificate or add the one in the repository in your keychain.

**Comment by notedit** [comment]
yes
